import type { Initiative, Epic, Task, Worktree, Run } from './types'

// --- Initiatives (3) ---

export const mockInitiatives: Initiative[] = [
  {
    id: 'init-1',
    name: 'AI Dev Platform',
    color: '#00f0ff',
    status: 'active',
    summary: 'Core AI-assisted development platform with agent orchestration',
  },
  {
    id: 'init-2',
    name: 'Observability Stack',
    color: '#00ff88',
    status: 'active',
    summary: 'Real-time monitoring, tracing, and alerting infrastructure',
  },
  {
    id: 'init-3',
    name: 'Developer Portal',
    color: '#ffaa00',
    status: 'paused',
    summary: 'Self-service portal for onboarding, docs, and API management',
  },
]

// --- Epics (6) ---

export const mockEpics: Epic[] = [
  {
    id: 'epic-1',
    name: 'Codebase Hygiene',
    initiativeId: 'init-1',
    status: 'active',
    summary: 'Reduce tech debt and improve code quality across the platform',
  },
  {
    id: 'epic-2',
    name: 'Agent Orchestration',
    initiativeId: 'init-1',
    status: 'active',
    summary: 'Multi-agent coordination, scheduling, and lifecycle management',
  },
  {
    id: 'epic-3',
    name: 'Trace Pipeline',
    initiativeId: 'init-2',
    status: 'active',
    summary: 'Distributed tracing collection, storage, and query engine',
  },
  {
    id: 'epic-4',
    name: 'Alert Engine',
    initiativeId: 'init-2',
    status: 'active',
    summary: 'Rule-based alerting with escalation and notification channels',
  },
  {
    id: 'epic-5',
    name: 'API Gateway',
    initiativeId: 'init-3',
    status: 'paused',
    summary: 'Unified API gateway with rate limiting and auth',
  },
  {
    id: 'epic-6',
    name: 'Doc Generator',
    initiativeId: 'init-3',
    status: 'active',
    summary: 'Auto-generate API docs from OpenAPI specs',
  },
]

// --- Tasks (10) ---

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    name: 'Reduce Scheduler Slop',
    epicId: 'epic-1',
    initiativeId: 'init-1',
    status: 'active',
  },
  {
    id: 'task-2',
    name: 'Fix Memory Leaks',
    epicId: 'epic-1',
    initiativeId: 'init-1',
    status: 'active',
  },
  {
    id: 'task-3',
    name: 'Agent Heartbeat Protocol',
    epicId: 'epic-2',
    initiativeId: 'init-1',
    status: 'complete',
  },
  {
    id: 'task-4',
    name: 'Agent Pool Scaling',
    epicId: 'epic-2',
    initiativeId: 'init-1',
    status: 'active',
  },
  {
    id: 'task-5',
    name: 'Span Ingestion',
    epicId: 'epic-3',
    initiativeId: 'init-2',
    status: 'active',
  },
  {
    id: 'task-6',
    name: 'Trace Query API',
    epicId: 'epic-3',
    initiativeId: 'init-2',
    status: 'queued',
  },
  {
    id: 'task-7',
    name: 'Alert Rule DSL',
    epicId: 'epic-4',
    initiativeId: 'init-2',
    status: 'active',
  },
  {
    id: 'task-8',
    name: 'Slack Notifier',
    epicId: 'epic-4',
    initiativeId: 'init-2',
    status: 'complete',
  },
  {
    id: 'task-9',
    name: 'Rate Limiter',
    epicId: 'epic-5',
    initiativeId: 'init-3',
    status: 'paused',
  },
  {
    id: 'task-10',
    name: 'OpenAPI Parser',
    epicId: 'epic-6',
    initiativeId: 'init-3',
    status: 'active',
  },
]

// --- Worktrees (4) ---

export const mockWorktrees: Worktree[] = [
  {
    id: 'wt-1',
    name: 'feat/scheduler-priority',
    branch: 'feat/scheduler-priority',
    repo: 'acme/platform-core',
    worktreePath: '/home/dev/worktrees/scheduler-priority',
  },
  {
    id: 'wt-2',
    name: 'feat/agent-pool',
    branch: 'feat/agent-pool',
    repo: 'acme/platform-core',
    worktreePath: '/home/dev/worktrees/agent-pool',
  },
  {
    id: 'wt-3',
    name: 'feat/trace-pipeline',
    branch: 'feat/trace-pipeline',
    repo: 'acme/observability',
    worktreePath: '/home/dev/worktrees/trace-pipeline',
  },
  {
    id: 'wt-4',
    name: 'feat/api-docs',
    branch: 'feat/api-docs',
    repo: 'acme/dev-portal',
    worktreePath: '/home/dev/worktrees/api-docs',
  },
]

// --- Runs (14) ---

// Reuse the existing mockRun data for R-241
import { mockRun } from '../data/mock'

export const mockRuns: Run[] = [
  {
    ...mockRun,
    taskId: 'task-1',
    worktreeId: 'wt-1',
    createdAt: '2026-03-10T14:30:00Z',
    port: null,
    backend: null,
  },
  {
    id: 'R-242',
    status: 'idle',
    background: false,
    blocked: false,
    sessionId: 'CLD-4093',
    initiative: 'AI Dev Platform',
    epic: 'Codebase Hygiene',
    task: 'Fix Memory Leaks',
    repo: 'acme/platform-core',
    worktree: 'feat/scheduler-priority',
    touchedFiles: [
      { id: 'f10', name: 'pool.go', path: 'pkg/pool', additions: 45, deletions: 12, kind: 'code' },
      { id: 'f11', name: 'pool_test.go', path: 'pkg/pool', additions: 30, deletions: 0, kind: 'test' },
    ],
    recapEntries: [
      { id: 'r10', type: 'agent', content: 'Fixed goroutine leak in pool manager. Added deferred cleanup.', timestamp: '15:10:00' },
    ],
    rawLogs: '[15:10:00] Fixed goroutine leak in pool manager',
    taskId: 'task-2',
    worktreeId: 'wt-1',
    createdAt: '2026-03-10T15:00:00Z',
    port: null,
    backend: null,
  },
  {
    id: 'R-243',
    status: 'stopped',
    background: false,
    blocked: false,
    sessionId: 'CLD-4094',
    initiative: 'AI Dev Platform',
    epic: 'Agent Orchestration',
    task: 'Agent Heartbeat Protocol',
    repo: 'acme/platform-core',
    worktree: 'feat/agent-pool',
    touchedFiles: [
      { id: 'f12', name: 'heartbeat.go', path: 'pkg/agent', additions: 89, deletions: 0, kind: 'code' },
      { id: 'f13', name: 'heartbeat_test.go', path: 'pkg/agent', additions: 56, deletions: 0, kind: 'test' },
      { id: 'f14', name: 'agent.proto', path: 'proto/', additions: 12, deletions: 0, kind: 'config' },
    ],
    recapEntries: [
      { id: 'r12', type: 'agent', content: 'Implemented heartbeat protocol with 5s interval and 3-miss threshold.', timestamp: '10:00:00' },
    ],
    rawLogs: '[10:00:00] Heartbeat protocol implementation complete',
    taskId: 'task-3',
    worktreeId: 'wt-2',
    createdAt: '2026-03-10T10:00:00Z',
    port: null,
    backend: null,
  },
  {
    id: 'R-244',
    status: 'running',
    background: false,
    blocked: false,
    sessionId: 'CLD-4095',
    initiative: 'AI Dev Platform',
    epic: 'Agent Orchestration',
    task: 'Agent Pool Scaling',
    repo: 'acme/platform-core',
    worktree: 'feat/agent-pool',
    touchedFiles: [
      { id: 'f15', name: 'autoscaler.go', path: 'pkg/scale', additions: 134, deletions: 0, kind: 'code' },
      { id: 'f16', name: 'metrics.go', path: 'pkg/scale', additions: 45, deletions: 0, kind: 'code' },
    ],
    recapEntries: [
      { id: 'r14', type: 'agent', content: 'Building autoscaler with queue-depth-based scaling policy.', timestamp: '16:00:00' },
      { id: 'r15', type: 'status', content: 'Running unit tests...', timestamp: '16:05:00' },
    ],
    rawLogs: '[16:00:00] Autoscaler implementation in progress',
    taskId: 'task-4',
    worktreeId: 'wt-2',
    createdAt: '2026-03-10T16:00:00Z',
    port: null,
    backend: null,
  },
  {
    id: 'R-245',
    status: 'running',
    background: false,
    blocked: false,
    sessionId: 'CLD-4096',
    initiative: 'Observability Stack',
    epic: 'Trace Pipeline',
    task: 'Span Ingestion',
    repo: 'acme/observability',
    worktree: 'feat/trace-pipeline',
    touchedFiles: [
      { id: 'f17', name: 'ingest.go', path: 'pkg/trace', additions: 200, deletions: 15, kind: 'code' },
      { id: 'f18', name: 'batch.go', path: 'pkg/trace', additions: 87, deletions: 0, kind: 'code' },
      { id: 'f19', name: 'ingest_test.go', path: 'pkg/trace', additions: 120, deletions: 0, kind: 'test' },
    ],
    recapEntries: [
      { id: 'r16', type: 'agent', content: 'Implementing batch span ingestion with configurable flush interval.', timestamp: '11:00:00' },
    ],
    rawLogs: '[11:00:00] Span ingestion batch implementation',
    taskId: 'task-5',
    worktreeId: 'wt-3',
    createdAt: '2026-03-10T11:00:00Z',
    port: null,
    backend: null,
  },
  {
    id: 'R-246',
    status: 'idle',
    background: false,
    blocked: false,
    sessionId: 'CLD-4097',
    initiative: 'Observability Stack',
    epic: 'Trace Pipeline',
    task: 'Trace Query API',
    repo: 'acme/observability',
    worktree: 'feat/trace-pipeline',
    touchedFiles: [],
    recapEntries: [],
    rawLogs: '',
    taskId: 'task-6',
    worktreeId: 'wt-3',
    createdAt: '2026-03-10T17:00:00Z',
    port: null,
    backend: null,
  },
  {
    id: 'R-247',
    status: 'running',
    background: false,
    blocked: false,
    sessionId: 'CLD-4098',
    initiative: 'Observability Stack',
    epic: 'Alert Engine',
    task: 'Alert Rule DSL',
    repo: 'acme/observability',
    worktree: 'feat/trace-pipeline',
    touchedFiles: [
      { id: 'f20', name: 'dsl.go', path: 'pkg/alert', additions: 156, deletions: 0, kind: 'code' },
      { id: 'f21', name: 'parser.go', path: 'pkg/alert', additions: 230, deletions: 0, kind: 'code' },
      { id: 'f22', name: 'dsl_test.go', path: 'pkg/alert', additions: 90, deletions: 0, kind: 'test' },
    ],
    recapEntries: [
      { id: 'r17', type: 'agent', content: 'Designing alert DSL grammar with threshold, window, and comparison operators.', timestamp: '12:00:00' },
    ],
    rawLogs: '[12:00:00] Alert DSL grammar design',
    taskId: 'task-7',
    worktreeId: 'wt-3',
    createdAt: '2026-03-10T12:00:00Z',
    port: null,
    backend: null,
  },
  {
    id: 'R-248',
    status: 'stopped',
    background: false,
    blocked: false,
    sessionId: 'CLD-4099',
    initiative: 'Observability Stack',
    epic: 'Alert Engine',
    task: 'Slack Notifier',
    repo: 'acme/observability',
    worktree: 'feat/trace-pipeline',
    touchedFiles: [
      { id: 'f23', name: 'slack.go', path: 'pkg/notify', additions: 78, deletions: 0, kind: 'code' },
      { id: 'f24', name: 'slack_test.go', path: 'pkg/notify', additions: 45, deletions: 0, kind: 'test' },
    ],
    recapEntries: [
      { id: 'r18', type: 'agent', content: 'Slack webhook integration complete with message formatting.', timestamp: '09:30:00' },
    ],
    rawLogs: '[09:30:00] Slack notifier implementation complete',
    taskId: 'task-8',
    worktreeId: 'wt-3',
    createdAt: '2026-03-10T09:00:00Z',
    port: null,
    backend: null,
  },
  {
    id: 'R-249',
    status: 'idle',
    background: false,
    blocked: false,
    sessionId: 'CLD-4100',
    initiative: 'Developer Portal',
    epic: 'API Gateway',
    task: 'Rate Limiter',
    repo: 'acme/dev-portal',
    worktree: 'feat/api-docs',
    touchedFiles: [
      { id: 'f25', name: 'ratelimit.ts', path: 'src/middleware', additions: 67, deletions: 0, kind: 'code' },
    ],
    recapEntries: [
      { id: 'r19', type: 'agent', content: 'Token bucket rate limiter with Redis backend. Paused per initiative status.', timestamp: '13:00:00' },
    ],
    rawLogs: '[13:00:00] Rate limiter paused',
    taskId: 'task-9',
    worktreeId: 'wt-4',
    createdAt: '2026-03-10T13:00:00Z',
    port: null,
    backend: null,
  },
  {
    id: 'R-250',
    status: 'running',
    background: false,
    blocked: false,
    sessionId: 'CLD-4101',
    initiative: 'Developer Portal',
    epic: 'Doc Generator',
    task: 'OpenAPI Parser',
    repo: 'acme/dev-portal',
    worktree: 'feat/api-docs',
    touchedFiles: [
      { id: 'f26', name: 'parser.ts', path: 'src/openapi', additions: 189, deletions: 0, kind: 'code' },
      { id: 'f27', name: 'schema.ts', path: 'src/openapi', additions: 56, deletions: 0, kind: 'code' },
      { id: 'f28', name: 'parser.test.ts', path: 'src/openapi', additions: 78, deletions: 0, kind: 'test' },
    ],
    recapEntries: [
      { id: 'r20', type: 'agent', content: 'Parsing OpenAPI 3.1 specs. Extracting endpoint metadata and schema refs.', timestamp: '14:00:00' },
    ],
    rawLogs: '[14:00:00] OpenAPI parser in progress',
    taskId: 'task-10',
    worktreeId: 'wt-4',
    createdAt: '2026-03-10T14:00:00Z',
    port: null,
    backend: null,
  },
  {
    id: 'R-251',
    status: 'stopped',
    background: false,
    blocked: false,
    sessionId: 'CLD-4102',
    initiative: 'AI Dev Platform',
    epic: 'Codebase Hygiene',
    task: 'Reduce Scheduler Slop',
    repo: 'acme/platform-core',
    worktree: 'feat/scheduler-priority',
    touchedFiles: [
      { id: 'f29', name: 'scheduler_v2.go', path: 'pkg/api/v2', additions: 45, deletions: 0, kind: 'code' },
    ],
    recapEntries: [
      { id: 'r21', type: 'agent', content: 'Attempted v2 scheduler refactor but hit circular dependency.', timestamp: '08:00:00' },
      { id: 'r22', type: 'status', content: 'Build failed: import cycle detected', timestamp: '08:15:00' },
    ],
    rawLogs: '[08:15:00] Build failed: import cycle detected',
    taskId: 'task-1',
    worktreeId: 'wt-1',
    createdAt: '2026-03-10T08:00:00Z',
    port: null,
    backend: null,
  },
  {
    id: 'R-252',
    status: 'running',
    background: false,
    blocked: false,
    sessionId: 'CLD-4103',
    initiative: 'AI Dev Platform',
    epic: 'Agent Orchestration',
    task: 'Agent Pool Scaling',
    repo: 'acme/platform-core',
    worktree: 'feat/agent-pool',
    touchedFiles: [
      { id: 'f30', name: 'pool_manager.go', path: 'pkg/pool', additions: 98, deletions: 23, kind: 'code' },
      { id: 'f31', name: 'pool_manager_test.go', path: 'pkg/pool', additions: 67, deletions: 0, kind: 'test' },
    ],
    recapEntries: [
      { id: 'r23', type: 'agent', content: 'Refactoring pool manager for dynamic scaling support.', timestamp: '16:30:00' },
    ],
    rawLogs: '[16:30:00] Pool manager refactoring',
    taskId: 'task-4',
    worktreeId: 'wt-2',
    createdAt: '2026-03-10T16:30:00Z',
    port: null,
    backend: null,
  },
  {
    id: 'R-253',
    status: 'running',
    background: false,
    blocked: false,
    sessionId: 'CLD-4104',
    initiative: 'Observability Stack',
    epic: 'Trace Pipeline',
    task: 'Span Ingestion',
    repo: 'acme/observability',
    worktree: 'feat/trace-pipeline',
    touchedFiles: [
      { id: 'f32', name: 'compressor.go', path: 'pkg/trace', additions: 67, deletions: 0, kind: 'code' },
    ],
    recapEntries: [
      { id: 'r24', type: 'agent', content: 'Adding zstd compression for span payloads.', timestamp: '11:30:00' },
    ],
    rawLogs: '[11:30:00] Span compression implementation',
    taskId: 'task-5',
    worktreeId: 'wt-3',
    createdAt: '2026-03-10T11:30:00Z',
    port: null,
    backend: null,
  },
  {
    id: 'R-254',
    status: 'stopped',
    background: false,
    blocked: false,
    sessionId: 'CLD-4105',
    initiative: 'Developer Portal',
    epic: 'Doc Generator',
    task: 'OpenAPI Parser',
    repo: 'acme/dev-portal',
    worktree: 'feat/api-docs',
    touchedFiles: [
      { id: 'f33', name: 'renderer.ts', path: 'src/openapi', additions: 120, deletions: 0, kind: 'code' },
      { id: 'f34', name: 'renderer.test.ts', path: 'src/openapi', additions: 55, deletions: 0, kind: 'test' },
    ],
    recapEntries: [
      { id: 'r25', type: 'agent', content: 'HTML renderer for parsed OpenAPI specs complete.', timestamp: '14:45:00' },
    ],
    rawLogs: '[14:45:00] Renderer implementation complete',
    taskId: 'task-10',
    worktreeId: 'wt-4',
    createdAt: '2026-03-10T14:30:00Z',
    port: null,
    backend: null,
  },
]
