// Rewrites root-relative URLs in proxied browser-widget responses so they route
// back through /api/proxy/{widgetId}/… instead of resolving against the Tinstar
// origin. Pure + exported so the logic is unit-tested independently of the HTTP
// plumbing in routes.ts.
//
// HTML/CSS/JSON are rewritten at the source level. JavaScript is NOT: you cannot
// reliably tell a string literal ("/api") from a regex-literal delimiter (/"/g)
// or a regex-then-string sequence (/"/g, "x") with a regex — any such rewrite
// corrupts valid JS. Instead, root-relative URLs generated by JS are handled at
// runtime by a shim (proxyRuntimeShim) injected into the proxied HTML, which
// patches fetch/XHR/serviceWorker so JS source stays byte-exact.

/**
 * Rewrite quoted root-relative string-literal paths: "/foo" → "{proxyBase}/foo"
 * (and the same for single quotes). Requires a matching closing quote so it only
 * touches genuine string literals; protocol-relative "//cdn" URLs are left alone.
 * Safe for HTML attributes, JSON values, and CSS — NOT used on JS (see file header).
 */
export function rewriteQuotedPaths(s: string, proxyBase: string): string {
  return s.replace(/(["'])\/(?!\/)([^"'\n]*?)\1/g, `$1${proxyBase}/$2$1`)
}

/** Rewrite unquoted CSS url(/foo) → url({proxyBase}/foo) (skip protocol-relative). */
export function rewriteCssUrls(s: string, proxyBase: string): string {
  return s.replace(/url\(\/(?!\/)([^)]*)\)/g, `url(${proxyBase}/$1)`)
}

/**
 * Rewrite a proxied response body by content type.
 * - HTML: rewrite quoted paths in the non-<script> segments; inline scripts are left
 *   untouched (executable JS — handled at runtime by the injected shim).
 * - JavaScript: returned byte-exact. Source rewriting would corrupt regex literals.
 * - JSON / CSS / text: rewrite quoted paths.
 * CSS url() rewriting is applied afterwards to everything except JS.
 */
export function rewriteProxyBody(body: string, contentType: string, proxyBase: string): string {
  const ct = contentType.toLowerCase()
  if (ct.includes('javascript')) {
    // Never touch executable JS — root-relative URLs it generates are rewritten at
    // runtime by the shim injected into the host HTML.
    return body
  }
  let out: string
  if (ct.includes('text/html')) {
    // split() with a capturing group keeps <script>…</script> blocks as odd-index
    // elements; rewrite only the even-index (non-script) segments.
    out = body
      .split(/(<script\b[\s\S]*?<\/script>)/gi)
      .map((part, i) => (i % 2 === 0 ? rewriteQuotedPaths(part, proxyBase) : part))
      .join('')
  } else {
    out = rewriteQuotedPaths(body, proxyBase)
  }
  return rewriteCssUrls(out, proxyBase)
}

/**
 * Map a single URL (as seen by client-side fetch/XHR/etc.) to its proxied form:
 * a root-relative "/foo" becomes "{proxyBase}/foo"; protocol-relative ("//cdn"),
 * absolute (with scheme), and non-root-relative URLs are returned unchanged. Pure
 * so the shim's behavior is unit-tested directly. Exported and also serialized into
 * the runtime shim below (kept trivial so it survives stringification).
 */
export function rewriteUrlForProxy(url: string, proxyBase: string): string {
  if (typeof url !== 'string') return url
  if (url.length < 1 || url[0] !== '/' || url[1] === '/') return url // not root-relative (or protocol-relative)
  // Idempotent: a URL already under the proxy base must not be prefixed again.
  // A proxied app can derive its own base from location.pathname (the stretchplan
  // SPA does: BASE = pathname before '/p/<slug>') and emit /api/proxy/<id>/plans/x
  // itself; re-prefixing would yield /api/proxy/<id>/api/proxy/<id>/plans/x (404).
  if (url === proxyBase || url.indexOf(proxyBase + '/') === 0) return url
  return proxyBase + url
}

/**
 * A self-contained <script> body (no surrounding tags) that patches the proxied
 * page's fetch / XMLHttpRequest.open / navigator.serviceWorker.register so that
 * root-relative URLs route back through the proxy. This is how JS-generated URLs
 * are handled without rewriting JS source. Injected into the proxied HTML head.
 */
export function proxyRuntimeShim(proxyBase: string): string {
  const base = JSON.stringify(proxyBase)
  return (
    `(function(){var B=${base};` +
    `function rw(u){if(typeof u!=='string'||u.length<1||u[0]!=='/'||u[1]==='/')return u;` +
    `if(u===B||u.indexOf(B+'/')===0)return u;return B+u;}` +
    `var of=window.fetch;if(of){window.fetch=function(i,o){` +
    `try{i=(typeof i==='string')?rw(i):(i&&i.url?new Request(rw(i.url),i):i);}catch(e){}` +
    `return of.call(this,i,o);};}` +
    `var XO=window.XMLHttpRequest&&window.XMLHttpRequest.prototype.open;` +
    `if(XO){window.XMLHttpRequest.prototype.open=function(m,u){` +
    `arguments[1]=rw(u);return XO.apply(this,arguments);};}` +
    `try{if(navigator.serviceWorker&&navigator.serviceWorker.register){` +
    `var SR=navigator.serviceWorker.register.bind(navigator.serviceWorker);` +
    `navigator.serviceWorker.register=function(u,o){return SR(rw(u),o);};}}catch(e){}` +
    `})()`
  )
}
