import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import {
  findTranscriptByConvId,
  readSessionStatusDetailAt,
  readLatestModelAt,
} from '../transcript-parser'

let scratch: string

beforeEach(() => {
  scratch = mkdtempSync(join(tmpdir(), 'tinstar-parser-'))
})

afterEach(() => {
  rmSync(scratch, { recursive: true, force: true })
})

function writeTranscript(projectDirName: string, convId: string, lines: object[]): string {
  const projectDir = join(scratch, projectDirName)
  mkdirSync(projectDir, { recursive: true })
  const path = join(projectDir, `${convId}.jsonl`)
  writeFileSync(path, lines.map(l => JSON.stringify(l)).join('\n') + '\n')
  return path
}

describe('findTranscriptByConvId', () => {
  it('returns null when no project dir contains the conversation id', () => {
    mkdirSync(join(scratch, '-some-other-project'), { recursive: true })
    expect(findTranscriptByConvId('missing-conv', scratch)).toBeNull()
  })

  it('finds a transcript across multiple project dirs', () => {
    writeTranscript('-home-other', 'aaaa', [{ type: 'user', message: { content: 'x' } }])
    const target = writeTranscript('-home-ubuntu-repo-tinstar', 'target-conv', [
      { type: 'assistant', message: { content: [{ type: 'text', text: 'hi' }] } },
    ])
    expect(findTranscriptByConvId('target-conv', scratch)).toBe(target)
  })

  it('returns null when the projects base dir does not exist', () => {
    expect(findTranscriptByConvId('whatever', join(scratch, 'nope'))).toBeNull()
  })
})

describe('readSessionStatusDetailAt', () => {
  it('returns null for missing path', () => {
    expect(readSessionStatusDetailAt(join(scratch, 'no-such.jsonl'))).toBeNull()
  })

  it('returns idle for assistant with only text blocks', () => {
    const path = writeTranscript('-p', 'c', [
      { type: 'user', message: { content: 'hello' } },
      { type: 'assistant', message: { content: [{ type: 'text', text: 'done' }] } },
    ])
    expect(readSessionStatusDetailAt(path)).toEqual({ state: 'idle', toolPending: false })
  })

  it('returns running with toolPending for assistant with tool_use blocks', () => {
    const path = writeTranscript('-p', 'c', [
      { type: 'user', message: { content: 'do x' } },
      {
        type: 'assistant',
        message: { content: [{ type: 'tool_use', name: 'Bash', input: {} }] },
      },
    ])
    expect(readSessionStatusDetailAt(path)).toEqual({ state: 'running', toolPending: true })
  })

  it('skips trailing metadata entries (system, attachment, last-prompt) when scanning back', () => {
    const path = writeTranscript('-p', 'c', [
      { type: 'user', message: { content: 'hi' } },
      { type: 'assistant', message: { content: [{ type: 'text', text: 'hello' }] } },
      { type: 'attachment' },
      { type: 'last-prompt' },
      { type: 'permission-mode' },
      { type: 'system' },
      { type: 'system' },
    ])
    expect(readSessionStatusDetailAt(path)).toEqual({ state: 'idle', toolPending: false })
  })

  it('skips trailing user records that are only bash-input/bash-stdout/local-command artifacts', () => {
    // Reproduces the bugDispatch case: agent finished a turn (idle), then the
    // user typed `! gsync` at the bash prompt, which appends user records that
    // contain only <local-command-caveat>/<bash-input>/<bash-stdout>. The
    // session is still idle (waiting for a real prompt), not running.
    const path = writeTranscript('-p', 'c', [
      { type: 'user', message: { content: 'hi' } },
      { type: 'assistant', message: { content: [{ type: 'text', text: 'hello' }] } },
      {
        type: 'user',
        message: {
          content:
            '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>',
        },
      },
      { type: 'user', message: { content: '<bash-input> gsync</bash-input>' } },
      {
        type: 'user',
        message: {
          content:
            '<bash-stdout></bash-stdout><bash-stderr>/bin/bash: line 1: gsync: command not found\n</bash-stderr>',
        },
      },
    ])
    expect(readSessionStatusDetailAt(path)).toEqual({ state: 'idle', toolPending: false })
  })

  it('still treats a real user prompt as running', () => {
    const path = writeTranscript('-p', 'c', [
      { type: 'assistant', message: { content: [{ type: 'text', text: 'hello' }] } },
      { type: 'user', message: { content: 'next prompt please' } },
    ])
    expect(readSessionStatusDetailAt(path)).toEqual({ state: 'running', toolPending: false })
  })
})

describe('readLatestModelAt', () => {
  it('returns null for a missing path', () => {
    expect(readLatestModelAt(join(scratch, 'no-such.jsonl'))).toBeNull()
  })

  it('returns null for an empty transcript', () => {
    const path = writeTranscript('-p', 'c', [])
    expect(readLatestModelAt(path)).toBeNull()
  })

  it("reads the latest assistant turn's message.model", () => {
    const path = writeTranscript('-p', 'c', [
      { type: 'user', message: { content: 'hi' } },
      {
        type: 'assistant',
        message: { model: 'claude-opus-4-8', content: [{ type: 'text', text: 'hello' }] },
      },
    ])
    expect(readLatestModelAt(path)).toBe('claude-opus-4-8')
  })

  it('returns the model of the LATEST assistant turn when the model changes', () => {
    const path = writeTranscript('-p', 'c', [
      {
        type: 'assistant',
        message: { model: 'claude-opus-4-8', content: [{ type: 'text', text: 'first' }] },
      },
      { type: 'user', message: { content: 'switch models' } },
      {
        type: 'assistant',
        message: { model: 'claude-haiku-4-5', content: [{ type: 'text', text: 'second' }] },
      },
    ])
    expect(readLatestModelAt(path)).toBe('claude-haiku-4-5')
  })

  it('reads the model even from an assistant turn carrying only tool_use blocks', () => {
    const path = writeTranscript('-p', 'c', [
      {
        type: 'assistant',
        message: {
          model: 'claude-sonnet-4-5',
          content: [{ type: 'tool_use', id: 't1', name: 'Read', input: {} }],
        },
      },
    ])
    expect(readLatestModelAt(path)).toBe('claude-sonnet-4-5')
  })

  it('returns null when there is no assistant turn yet (pre-first-response)', () => {
    const path = writeTranscript('-p', 'c', [
      { type: 'user', message: { content: 'first prompt, no response yet' } },
    ])
    expect(readLatestModelAt(path)).toBeNull()
  })

  it('returns null when an assistant turn carries no model field', () => {
    const path = writeTranscript('-p', 'c', [
      { type: 'assistant', message: { content: [{ type: 'text', text: 'no model key' }] } },
    ])
    expect(readLatestModelAt(path)).toBeNull()
  })

  it('skips trailing non-assistant metadata to find the last assistant model', () => {
    const path = writeTranscript('-p', 'c', [
      {
        type: 'assistant',
        message: { model: 'claude-opus-4-8', content: [{ type: 'text', text: 'done' }] },
      },
      { type: 'file-history-snapshot', snapshot: {} },
      { type: 'user', message: { content: '<bash-input> ls</bash-input>' } },
    ])
    expect(readLatestModelAt(path)).toBe('claude-opus-4-8')
  })
})
