import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import {
  findTranscriptByConvId,
  readSessionStatusDetailAt,
} from '../transcript-parser'

let scratch: string

beforeEach(() => {
  scratch = mkdtempSync(join(tmpdir(), 'tinstar-parser-'))
})

afterEach(() => {
  rmSync(scratch, { recursive: true, force: true })
})

function writeTranscript(projectDirName: string, convId: string, lines: object[]): string {
  const projectDir = join(scratch, projectDirName)
  mkdirSync(projectDir, { recursive: true })
  const path = join(projectDir, `${convId}.jsonl`)
  writeFileSync(path, lines.map(l => JSON.stringify(l)).join('\n') + '\n')
  return path
}

describe('findTranscriptByConvId', () => {
  it('returns null when no project dir contains the conversation id', () => {
    mkdirSync(join(scratch, '-some-other-project'), { recursive: true })
    expect(findTranscriptByConvId('missing-conv', scratch)).toBeNull()
  })

  it('finds a transcript across multiple project dirs', () => {
    writeTranscript('-home-other', 'aaaa', [{ type: 'user', message: { content: 'x' } }])
    const target = writeTranscript('-home-ubuntu-repo-tinstar', 'target-conv', [
      { type: 'assistant', message: { content: [{ type: 'text', text: 'hi' }] } },
    ])
    expect(findTranscriptByConvId('target-conv', scratch)).toBe(target)
  })

  it('returns null when the projects base dir does not exist', () => {
    expect(findTranscriptByConvId('whatever', join(scratch, 'nope'))).toBeNull()
  })
})

describe('readSessionStatusDetailAt', () => {
  it('returns null for missing path', () => {
    expect(readSessionStatusDetailAt(join(scratch, 'no-such.jsonl'))).toBeNull()
  })

  it('returns idle for assistant with only text blocks', () => {
    const path = writeTranscript('-p', 'c', [
      { type: 'user', message: { content: 'hello' } },
      { type: 'assistant', message: { content: [{ type: 'text', text: 'done' }] } },
    ])
    expect(readSessionStatusDetailAt(path)).toEqual({ state: 'idle', toolPending: false })
  })

  it('returns running with toolPending for assistant with tool_use blocks', () => {
    const path = writeTranscript('-p', 'c', [
      { type: 'user', message: { content: 'do x' } },
      {
        type: 'assistant',
        message: { content: [{ type: 'tool_use', name: 'Bash', input: {} }] },
      },
    ])
    expect(readSessionStatusDetailAt(path)).toEqual({ state: 'running', toolPending: true })
  })

  it('skips trailing metadata entries (system, attachment, last-prompt) when scanning back', () => {
    const path = writeTranscript('-p', 'c', [
      { type: 'user', message: { content: 'hi' } },
      { type: 'assistant', message: { content: [{ type: 'text', text: 'hello' }] } },
      { type: 'attachment' },
      { type: 'last-prompt' },
      { type: 'permission-mode' },
      { type: 'system' },
      { type: 'system' },
    ])
    expect(readSessionStatusDetailAt(path)).toEqual({ state: 'idle', toolPending: false })
  })

  it('skips trailing user records that are only bash-input/bash-stdout/local-command artifacts', () => {
    // Reproduces the bugDispatch case: agent finished a turn (idle), then the
    // user typed `! gsync` at the bash prompt, which appends user records that
    // contain only <local-command-caveat>/<bash-input>/<bash-stdout>. The
    // session is still idle (waiting for a real prompt), not running.
    const path = writeTranscript('-p', 'c', [
      { type: 'user', message: { content: 'hi' } },
      { type: 'assistant', message: { content: [{ type: 'text', text: 'hello' }] } },
      {
        type: 'user',
        message: {
          content:
            '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>',
        },
      },
      { type: 'user', message: { content: '<bash-input> gsync</bash-input>' } },
      {
        type: 'user',
        message: {
          content:
            '<bash-stdout></bash-stdout><bash-stderr>/bin/bash: line 1: gsync: command not found\n</bash-stderr>',
        },
      },
    ])
    expect(readSessionStatusDetailAt(path)).toEqual({ state: 'idle', toolPending: false })
  })

  it('still treats a real user prompt as running', () => {
    const path = writeTranscript('-p', 'c', [
      { type: 'assistant', message: { content: [{ type: 'text', text: 'hello' }] } },
      { type: 'user', message: { content: 'next prompt please' } },
    ])
    expect(readSessionStatusDetailAt(path)).toEqual({ state: 'running', toolPending: false })
  })
})
