import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { mkdtempSync, mkdirSync, writeFileSync, appendFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import {
  findTranscriptByConvId,
  readSessionStatusDetailAt,
  readLatestModelAt,
  parseNewEntriesAt,
  resetOffset,
  __resetModelCache,
} from '../transcript-parser'

let scratch: string

beforeEach(() => {
  scratch = mkdtempSync(join(tmpdir(), 'tinstar-parser-'))
  __resetModelCache() // module-global cache is keyed by path; reset so cases don't bleed
})

afterEach(() => {
  rmSync(scratch, { recursive: true, force: true })
})

function writeTranscript(projectDirName: string, convId: string, lines: object[]): string {
  const projectDir = join(scratch, projectDirName)
  mkdirSync(projectDir, { recursive: true })
  const path = join(projectDir, `${convId}.jsonl`)
  writeFileSync(path, lines.map(l => JSON.stringify(l)).join('\n') + '\n')
  return path
}

describe('findTranscriptByConvId', () => {
  it('returns null when no project dir contains the conversation id', () => {
    mkdirSync(join(scratch, '-some-other-project'), { recursive: true })
    expect(findTranscriptByConvId('missing-conv', scratch)).toBeNull()
  })

  it('finds a transcript across multiple project dirs', () => {
    writeTranscript('-home-other', 'aaaa', [{ type: 'user', message: { content: 'x' } }])
    const target = writeTranscript('-home-ubuntu-repo-tinstar', 'target-conv', [
      { type: 'assistant', message: { content: [{ type: 'text', text: 'hi' }] } },
    ])
    expect(findTranscriptByConvId('target-conv', scratch)).toBe(target)
  })

  it('returns null when the projects base dir does not exist', () => {
    expect(findTranscriptByConvId('whatever', join(scratch, 'nope'))).toBeNull()
  })
})

describe('readSessionStatusDetailAt', () => {
  it('returns null for missing path', () => {
    expect(readSessionStatusDetailAt(join(scratch, 'no-such.jsonl'))).toBeNull()
  })

  it('returns idle for assistant with only text blocks', () => {
    const path = writeTranscript('-p', 'c', [
      { type: 'user', message: { content: 'hello' } },
      { type: 'assistant', message: { content: [{ type: 'text', text: 'done' }] } },
    ])
    expect(readSessionStatusDetailAt(path)).toEqual({ state: 'idle', toolPending: false })
  })

  it('returns running with toolPending for assistant with tool_use blocks', () => {
    const path = writeTranscript('-p', 'c', [
      { type: 'user', message: { content: 'do x' } },
      {
        type: 'assistant',
        message: { content: [{ type: 'tool_use', name: 'Bash', input: {} }] },
      },
    ])
    expect(readSessionStatusDetailAt(path)).toEqual({ state: 'running', toolPending: true })
  })

  it('skips trailing metadata entries (system, attachment, last-prompt) when scanning back', () => {
    const path = writeTranscript('-p', 'c', [
      { type: 'user', message: { content: 'hi' } },
      { type: 'assistant', message: { content: [{ type: 'text', text: 'hello' }] } },
      { type: 'attachment' },
      { type: 'last-prompt' },
      { type: 'permission-mode' },
      { type: 'system' },
      { type: 'system' },
    ])
    expect(readSessionStatusDetailAt(path)).toEqual({ state: 'idle', toolPending: false })
  })

  it('skips trailing user records that are only bash-input/bash-stdout/local-command artifacts', () => {
    // Reproduces the bugDispatch case: agent finished a turn (idle), then the
    // user typed `! gsync` at the bash prompt, which appends user records that
    // contain only <local-command-caveat>/<bash-input>/<bash-stdout>. The
    // session is still idle (waiting for a real prompt), not running.
    const path = writeTranscript('-p', 'c', [
      { type: 'user', message: { content: 'hi' } },
      { type: 'assistant', message: { content: [{ type: 'text', text: 'hello' }] } },
      {
        type: 'user',
        message: {
          content:
            '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>',
        },
      },
      { type: 'user', message: { content: '<bash-input> gsync</bash-input>' } },
      {
        type: 'user',
        message: {
          content:
            '<bash-stdout></bash-stdout><bash-stderr>/bin/bash: line 1: gsync: command not found\n</bash-stderr>',
        },
      },
    ])
    expect(readSessionStatusDetailAt(path)).toEqual({ state: 'idle', toolPending: false })
  })

  it('still treats a real user prompt as running', () => {
    const path = writeTranscript('-p', 'c', [
      { type: 'assistant', message: { content: [{ type: 'text', text: 'hello' }] } },
      { type: 'user', message: { content: 'next prompt please' } },
    ])
    expect(readSessionStatusDetailAt(path)).toEqual({ state: 'running', toolPending: false })
  })
})

describe('parseNewEntriesAt — tool_use counting', () => {
  it('sums tool_use blocks across a turn onto the closing agent entry', () => {
    const session = 'tool-count-1'
    resetOffset(session)
    const path = writeTranscript('-p', 'tc1', [
      { type: 'user', message: { content: 'do a thing' } },
      { type: 'assistant', message: { content: [
        { type: 'tool_use', id: 'a', name: 'Read', input: {} },
        { type: 'tool_use', id: 'b', name: 'Grep', input: {} },
      ] } },
      { type: 'assistant', message: { content: [{ type: 'tool_use', id: 'c', name: 'Bash', input: {} }] } },
      { type: 'assistant', message: { content: [{ type: 'text', text: 'all done' }] } },
    ])
    const entries = parseNewEntriesAt(session, path)
    const agent = entries.find(e => e.type === 'agent')
    expect(agent?.content).toBe('all done')
    expect(agent?.toolUses).toBe(3)
  })

  it('reports 0 tool uses for a text-only turn', () => {
    const session = 'tool-count-2'
    resetOffset(session)
    const path = writeTranscript('-p', 'tc2', [
      { type: 'user', message: { content: 'hi' } },
      { type: 'assistant', message: { content: [{ type: 'text', text: 'hello' }] } },
    ])
    const agent = parseNewEntriesAt(session, path).find(e => e.type === 'agent')
    expect(agent?.toolUses).toBe(0)
  })

  it('counts tool uses independently per turn', () => {
    const session = 'tool-count-3'
    resetOffset(session)
    const path = writeTranscript('-p', 'tc3', [
      { type: 'user', message: { content: 'first' } },
      { type: 'assistant', message: { content: [{ type: 'tool_use', id: 'a', name: 'Read', input: {} }] } },
      { type: 'assistant', message: { content: [{ type: 'text', text: 'r1' }] } },
      { type: 'user', message: { content: 'second' } },
      { type: 'assistant', message: { content: [
        { type: 'tool_use', id: 'b', name: 'Read', input: {} },
        { type: 'tool_use', id: 'c', name: 'Edit', input: {} },
      ] } },
      { type: 'assistant', message: { content: [{ type: 'text', text: 'r2' }] } },
    ])
    const agents = parseNewEntriesAt(session, path).filter(e => e.type === 'agent')
    expect(agents.map(a => ({ text: a.content, tools: a.toolUses }))).toEqual([
      { text: 'r1', tools: 1 },
      { text: 'r2', tools: 2 },
    ])
  })
})

describe('readLatestModelAt', () => {
  it('returns null for a missing path', () => {
    expect(readLatestModelAt(join(scratch, 'no-such.jsonl'))).toBeNull()
  })

  it('returns null for an empty transcript', () => {
    const path = writeTranscript('-p', 'c', [])
    expect(readLatestModelAt(path)).toBeNull()
  })

  it("reads the latest assistant turn's message.model", () => {
    const path = writeTranscript('-p', 'c', [
      { type: 'user', message: { content: 'hi' } },
      {
        type: 'assistant',
        message: { model: 'claude-opus-4-8', content: [{ type: 'text', text: 'hello' }] },
      },
    ])
    expect(readLatestModelAt(path)).toBe('claude-opus-4-8')
  })

  it('returns the model of the LATEST assistant turn when the model changes', () => {
    const path = writeTranscript('-p', 'c', [
      {
        type: 'assistant',
        message: { model: 'claude-opus-4-8', content: [{ type: 'text', text: 'first' }] },
      },
      { type: 'user', message: { content: 'switch models' } },
      {
        type: 'assistant',
        message: { model: 'claude-haiku-4-5', content: [{ type: 'text', text: 'second' }] },
      },
    ])
    expect(readLatestModelAt(path)).toBe('claude-haiku-4-5')
  })

  it('reads the model even from an assistant turn carrying only tool_use blocks', () => {
    const path = writeTranscript('-p', 'c', [
      {
        type: 'assistant',
        message: {
          model: 'claude-sonnet-4-5',
          content: [{ type: 'tool_use', id: 't1', name: 'Read', input: {} }],
        },
      },
    ])
    expect(readLatestModelAt(path)).toBe('claude-sonnet-4-5')
  })

  it('returns null when there is no assistant turn yet (pre-first-response)', () => {
    const path = writeTranscript('-p', 'c', [
      { type: 'user', message: { content: 'first prompt, no response yet' } },
    ])
    expect(readLatestModelAt(path)).toBeNull()
  })

  it('returns null when an assistant turn carries no model field', () => {
    const path = writeTranscript('-p', 'c', [
      { type: 'assistant', message: { content: [{ type: 'text', text: 'no model key' }] } },
    ])
    expect(readLatestModelAt(path)).toBeNull()
  })

  it('skips trailing non-assistant metadata to find the last assistant model', () => {
    const path = writeTranscript('-p', 'c', [
      {
        type: 'assistant',
        message: { model: 'claude-opus-4-8', content: [{ type: 'text', text: 'done' }] },
      },
      { type: 'file-history-snapshot', snapshot: {} },
      { type: 'user', message: { content: '<bash-input> ls</bash-input>' } },
    ])
    expect(readLatestModelAt(path)).toBe('claude-opus-4-8')
  })
})

describe('readLatestModelAt — caching + sticky model', () => {
  it('keeps the last-known model when a busy tail pushes the assistant turn out of the window', () => {
    const path = writeTranscript('-p', 'sticky', [
      { type: 'assistant', message: { model: 'claude-opus-4-8', content: [{ type: 'text', text: 'hi' }] } },
    ])
    expect(readLatestModelAt(path)).toBe('claude-opus-4-8')

    // Append > 50 trailing non-assistant records, shoving the assistant turn past
    // the 50-line tail window. A fresh read would now find no model — the bug that
    // would flicker a busy session's model to "—".
    const noise = Array.from({ length: 60 }, (_, i) =>
      JSON.stringify({ type: 'user', message: { content: `noise ${i}` } })).join('\n') + '\n'
    appendFileSync(path, noise)

    expect(readLatestModelAt(path)).toBe('claude-opus-4-8') // sticky, not null
  })

  it('re-reads and returns the new model when the model actually changes', () => {
    const path = writeTranscript('-p', 'change', [
      { type: 'assistant', message: { model: 'claude-opus-4-8', content: [{ type: 'text', text: 'a' }] } },
    ])
    expect(readLatestModelAt(path)).toBe('claude-opus-4-8')

    appendFileSync(path, JSON.stringify({
      type: 'assistant', message: { model: 'claude-haiku-4-5', content: [{ type: 'text', text: 'b' }] },
    }) + '\n')

    // The append grows the file, invalidating the (mtime,size) cache key — the new
    // model is picked up rather than serving the stale cached value.
    expect(readLatestModelAt(path)).toBe('claude-haiku-4-5')
  })

  it('surfaces a new model after a sticky-null window (stickiness never wrongly pins)', () => {
    const path = writeTranscript('-p', 'unstick', [
      { type: 'assistant', message: { model: 'claude-opus-4-8', content: [{ type: 'text', text: 'a' }] } },
    ])
    expect(readLatestModelAt(path)).toBe('claude-opus-4-8')

    // Push the assistant out of the window → sticky 'opus'.
    appendFileSync(path, Array.from({ length: 60 }, (_, i) =>
      JSON.stringify({ type: 'user', message: { content: `n${i}` } })).join('\n') + '\n')
    expect(readLatestModelAt(path)).toBe('claude-opus-4-8')

    // A new assistant turn lands at the tail with a different model — must surface
    // the NEW model, not stay pinned to the sticky old one.
    appendFileSync(path, JSON.stringify({
      type: 'assistant', message: { model: 'claude-haiku-4-5', content: [{ type: 'text', text: 'b' }] },
    }) + '\n')
    expect(readLatestModelAt(path)).toBe('claude-haiku-4-5')
  })

  it('forgets the cached model when the transcript is deleted (ENOENT)', () => {
    const path = writeTranscript('-p', 'gone', [
      { type: 'assistant', message: { model: 'claude-opus-4-8', content: [{ type: 'text', text: 'x' }] } },
    ])
    expect(readLatestModelAt(path)).toBe('claude-opus-4-8')
    rmSync(path)
    expect(readLatestModelAt(path)).toBeNull()
  })
})
